# -*- coding: utf-8 -*-
"""Financial Fraud Detection5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D1XUL20zQbONv2cvR2nF17-rPgyGXG-z
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")
sns.set(style="whitegrid")

df=pd.read_csv("/content/AIML Dataset.csv")

df.head()

df.info()

df.columns

df["isFraud"].value_counts()

df["isFlaggedFraud"].value_counts()

df.isnull()

df.isnull().sum()

df.isnull().sum().sum()

df.shape

df.shape[0]

round ((df["isFraud"].value_counts() [1] / df.shape[0]) * 100,2)

df["type"].value_counts().plot(kind="bar", title= "Transaction Types", color = "Skyblue")
plt.xlabel("Transaction Types")
plt.ylabel("Count")

fraud_by_type = df.groupby("type")["isFraud"].mean().sort_values(ascending=False)
fraud_by_type.plot(kind="bar", title = "Fraud Rate By Type", color="salmon")
plt.ylabel("Fraud Rate")
plt.show()

fraud_by_type

df["amount"].describe()

df["amount"].describe().astype(int)

sns.histplot(np.log1p(df["amount"]), bins=100, kde = True, color = "green")
plt.title("Transaction Amount Distribution (Log Scale)")
plt.xlabel("Log (Amount + 1)")
plt.show()

sns.boxplot(data = df[df["amount"] < 50000], x= "isFraud", y="amount")
plt.title("Amount Vs isFraud (Filtered Under 50k )")
plt.show()

df["balancedDiffOrig"] = df["oldbalanceOrg"] - df["newbalanceOrig"]
df["balancedDiffDest"] = df["newbalanceDest"] - df["oldbalanceDest"]

(df["balancedDiffOrig"] < 0).sum()

(df["balancedDiffDest"] < 0).sum()

df.head(2)

frauds_per_step = df[df["isFraud"]== 1]["step"].value_counts().sort_index()
plt.plot(frauds_per_step.index , frauds_per_step.values, label="Frauds Per Step")
plt.xlabel("Step (Time)")
plt.ylabel("Number of Frauds")
plt.title("Frauds Over Time")
plt.grid(True)
plt.show()

df.drop(columns="step",inplace=True)

df.head()

top_senders = df["nameOrig"].value_counts().head(10)

top_senders

top_receivers = df["nameDest"].value_counts().head(10)

top_receivers

fraud_users = df[df["isFraud"]== 1] ["nameOrig"].value_counts().head(10)

fraud_users

fraud_types = df[df["type"].isin(["TRANSFER","CASH_OUT"])]

fraud_types.head()

fraud_types["type"].value_counts()

sns.countplot(data=fraud_types, x="type", hue="isFraud")
plt.title("Fraud Distribution in Transfer & Cash_Out")
plt.show()

corr = df[["amount","oldbalanceOrg","newbalanceOrig","oldbalanceDest","newbalanceDest","isFraud"]].corr()

corr

sns.heatmap(corr,annot=True,cmap="coolwarm", fmt=".2f")
plt.title("Correaltion Matrix")
plt.show()

zero_after_transfer = df[
    (df["oldbalanceOrg"] > 0) &
    (df["newbalanceOrig"] == 0) &
    (df["type"].isin(["TRANFER","CASH_OUT"]))
]

len(zero_after_transfer)

zero_after_transfer.head()

df["isFraud"].value_counts()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

df.head()

df_model = df.drop(["nameOrig","nameDest","isFlaggedFraud"], axis = 1)

df_model.head()

categorical = ["type"]
numeric = ["amount","oldbalanceOrg","newbalanceOrig","oldbalanceDest","newbalanceDest"]

y = df_model["isFraud"]
x = df_model.drop("isFraud", axis = 1)

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3, stratify=y)

preprocessor = ColumnTransformer(
    transformers = [
        ("num", StandardScaler(), numeric),
        ("cat", OneHotEncoder(drop = "first"), categorical)

    ],
    remainder="drop"
)

Pipeline = Pipeline([
    ("prep", preprocessor),
    ("clf", LogisticRegression(class_weight="balanced", max_iter=1000))
])

Pipeline.fit(x_train, y_train)

y_pred = Pipeline.predict(x_test)

print(classification_report(y_test,y_pred))

confusion_matrix(y_test,y_pred)

Pipeline.score(x_test, y_test) * 100

import joblib
joblib.dump(Pipeline,"fraud_detection_pipeline.pkl")

!pip install scikit-learn==1.6.1

!pip install -U gradio